name: Tests
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
        with:
          php_version: 7.4
          version: 2

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v3
        with:
          version: 9
          bootstrap: vendor/autoload.php
          args: tests